apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
        - name: spring-api
          image: 629231206010.dkr.ecr.eu-west-1.amazonaws.com/infoline-spring-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
